# Generated by Django 5.1.3 on 2024-11-30 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
