# Generated by Django 5.1.3 on 2024-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("percentage", models.IntegerField()),
            ],
        ),
    ]
