# Generated by Django 5.1.3 on 2024-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0004_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skills",
            name="image",
            field=models.ImageField(default="None", upload_to=""),
        ),
    ]
