# Generated by Django 5.1.3 on 2024-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio", "0005_skills_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skills",
            name="image",
            field=models.TextField(),
        ),
    ]
